### PR TITLE
feat: add deploy-job to config create/update

### PR DESCRIPTION
**Pull request by ctrox**
This makes it possible to configure deploy-jobs with configs.

mono-infra#845

### CODE REVIEW

**Comment by pawelkuc** [comment]
Just wondering if we need to show some `deploy-job` info (e.g. name of the job if there is a job configured) when we `Get deplo.io Project Configuration`. For now the get command for config gives us:
```
"NAME",
"SIZE",
"REPLICAS",
"PORT",
"ENVIRONMENT_VARIABLES",
"AGE",
```
which is almost everything we store in the `Config struct{}` minus `BasicAuth` and `DeployJob`.

**Review by pawelkuc — APPROVED** [review]

**Comment by ctrox** [comment]
> Just wondering if we need to show some `deploy-job` info (e.g. name of the job if there is a job configured) when we `Get deplo.io Project Configuration`.

Was also thinking about that but a deploy-job has 4 different attributes, so adding 4 more columns would make the already wide output incredibly wide 😄

**Comment by ctrox** [comment]
@pawelkuc I added a commit, it now looks like this:

```bash
$ nctl get config
NAME    SIZE     REPLICAS    PORT    ENVIRONMENT_VARIABLES    BASIC_AUTH    DEPLOY_JOB    AGE
nine    micro    0           8080    <none>                   false         <none>        75d
```

**Comment by pawelkuc** [comment]
looks good! thank you 😄

**Pull request merged**
