### PR TITLE
Tag pulled build images with latest

### PR DESCRIPTION
**Pull request by ctrox**
Without a tag, using the pulled image with docker/podman is a bit cumbersome as you have to first find out the image ID. With a tag it's possible to just do `docker run <image name>`.

### CODE REVIEW

**Comment by gajicdev** [comment]
should we maybe add a way of passing a "custom" tag?

**Comment by ctrox** [comment]
> should we maybe add a way of passing a "custom" tag?

Not sure, you can still that afterwards using `docker tag`. But now that you mention it, it would make sense to add a tag with the build name in addition of the `latest` tag. So if you pull multiple versions you can easily tell them apart by the build name but the latest pulled will be the latest, making it easy to do a `docker run` without being specific about the tag.

**Comment by gajicdev** [comment]
yeah that would be great. Just in case you want to compare the versions locally 👍

**Review by gajicdev — APPROVED** [review]
looks good 👍

**Pull request merged**
